### ISSUE TITLE
The customer is facing issues implementing the ability to include YAML file inside a another YAML file

### ISSUE THREAD

**Issue by salapatt** [signalfx/splunk-otel-collector#3146]
https://github.com/signalfx/splunk-otel-collector/tree/main/internal/configsource/includeconfigsource#:~:text=The%20config%20source%20can%20be%20used%20to%20insert%20complete%20sections%20of%20the%20configuration%3A

When you include another yaml file, such as:
`${include:/etc/configs/exporters.yaml}`

Any env vars within that file are interpreted literally. So, we can't have:
`exporters: ${include:/etc/configs/exporters.yaml}`

where exporters.yaml is:
```
signalfx:
  access_token: "${SPLUNK_ACCESS_TOKEN}"
  api_url: "${SPLUNK_API_URL}"
  ingest_url: "${SPLUNK_INGEST_URL}"
  sync_host_metadata: true
```
Here, the collector will try hitting the api_url: "${SPLUNK_API_URL}" as opposed to what is actually stored in that env var.

**Comment by dil-mlucas** [comment]
Thanks for the assist here Shibu. This was created from a splunk support case I had opened up, but I am afraid this is only part of the problem. I will outline the rest below.

There is no ability to include multiple yaml injections, or the steps to do so are not outlined in documentation. It would be very useful if you could do something like:

receivers: ${include:/etc/configs/receiversOne.yaml}, ${include:/etc/configs/receiversTwo.yaml}

But there is nothing in the docs that alludes to this capability.

Our final problem lies with the smartagent/telegraf/exec plugin. When attempting to have config such as:

smartagent/exec:
type: telegraf/exec
command: 'go run /opt/splunk/scripts/myGoScript.go'
intervalSeconds: 600
telegrafParser:
dataFormat: value
dataType: string

The collector fails to find golang in the $PATH of the system, even though it is clearly outlined. I suspect this is because telegraf/exec was written in golang using the os.exec package, which by default does not have awareness of $PATH or other env vars. We need the ability for telegraf/exec to understand env/path vars, whether that be a flag we can set in the plugin, or if it is rewritten with different use of the os.exec package.

**Comment by rmfitzpatrick** [comment]
Thanks for the report @salapatt and @dil-mlucas. Unfortunately glob style imports in the include config source aren't currently supported and we're investigating a desired approach to be able to land the functionality. It's possible that improving the file config provider per https://github.com/open-telemetry/opentelemetry-collector/issues/7177 would be preferable.

Regarding the telegraf/exec path issue, I wasn't able to reproduce (investigation part of https://github.com/signalfx/splunk-otel-collector/pull/3183) and `PATH` values appear available to the exec input plugin. I believe that `os.Exec` as used by the input plugin will provide the parent env to the subprocess, and even appears to scan the `PATH` for the absolute executable path: https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/os/exec/exec.go;l=419. More information about how you are running the collector would be needed if go is resolvable from the PATH, ideally in a separate ticket to distinguish the issue from the include config source feature.

**Comment by rmfitzpatrick** [comment]
@salapatt regarding the unexpanded `"${SPLUNK_API_URL}"` issue, this does appear to be a problem but I believe using `"${env:SPLUNK_API_URL}"` is a valid workaround. The core config resolution process has been migrating to that approach as well.

**Comment by dil-mlucas** [comment]
Thanks @rmfitzpatrick. I was able to use the ${env:} syntax, but not on 0.73.0. I was only successful in using that from 0.76.1. Regardless, it should allow me to get creative enough to implement a decent solution. 

That's strange with telegraf exec... Perhaps it's another issue local to 0.73.0? I haven't tested on the latest release. But, since I can use env vars in my receivers "include" now, I can pass a var for the go path. (The reason I would prefer to not hardcode the path to the executable is that I would like my config to work on both linux and windows, universally.)

As for including multiple yaml files, that would be cool. We have a rather complex environment and the need for a lot of different configuration options. We were hoping to implement a modular, decentralized approach with a delivery pipeline - where people can pick and choose from available receivers, exporters, processors, or make their own, and mix and match with any number of them.

**Comment by dil-mlucas** [comment]
@rmfitzpatrick well, not that I can use env vars in the includes, I am just adding an entry with the go path, and doing something like:

```
smartagent/exec:
  type: telegraf/exec
  command: '${env:go_path} /opt/splunk/scripts/myGoScript.go'
  intervalSeconds: 600
  telegrafParser:
    dataFormat: value
    dataType: string

```

so the telegraf exec thing isn't a big issue anymore. Thanks for the help here!
