### ISSUE TITLE
Update Fargate README to include setup for accepting data on receivers

### ISSUE THREAD

**Issue by kdroukman** [signalfx/splunk-otel-collector#862]
The current instructions provide basic details for gathering ECS Fargate infrastructure data:
https://github.com/signalfx/splunk-otel-collector/tree/main/deployments/fargate

Can this be updated to include examples of accepting traces from apps within the task, eg. include ports that need to be mapped to receive spans on.

**Comment by atoulme** [comment]
The documentation points to the fargate default configuration file here:
https://github.com/signalfx/splunk-otel-collector/blob/main/cmd/otelcol/config/collector/fargate_config.yaml

It contains definitions of receivers with specific ports to target. Hopefully this is good enough to get you going.

Since this issue is rather old, I'm going to close it, please feel free to open new issues for any further work.
